### ISSUE TITLE
Investigate potential rsync issue on Windows

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-cli#110]
On at least one occasion on Windows the following error occurred during the upload of many (tens of thousands) of files.
```
message "0 [main] rsync 4536 cygwin_exception::open_stackdumpfile:
Dumping stack trace to rsync.exe.stackdump" but it is still working... any
```

It's unclear whether this is a bug in one of the bundled dependencies or if it's something we cause with one of the annex/rsync options we use.

**Comment by achilleas-k** [comment]
Outdated.  There's been a lot of testing on Windows without this appearing again and I haven't been able to reproduce or figure out what caused this.

**Comment by batata004** [comment]
Hapenned with me today (Nov/2022) using latest CYGWIN.
