### ISSUE TITLE
JSON output for Windows GUI client

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-cli#118]
gin-cli should have a `--json` flag much like git annex so that the Windows client, or user scripts, can parse the output easily.

Most commands that output file lists should support this.
- [x] ls
- [x] upload and download
- [x] lock and unlock

**Comment by The-E** [comment]
In particular, I would need gin ls to output things as JSON.

**Comment by achilleas-k** [comment]
I'll do that one first.

**Comment by achilleas-k** [comment]
See PR #126
