### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by yarikoptic** [G-Node/gin-cli#125]
Would you be so kind to point me to some kind of API to the beast, so we could may be establish access to the "public" datasets available from https://web.gin.g-node.org via datalad, without coming up with some ad-hoc crawler ;) 
 Needed pieces would be to just
- "protocol" to login and to "git clone"
- discover the list of organization/datasets
- fetch any available metadata associated with the datasets (authors, etc) if e.g. they are also "registered" (I see some at https://doid.gin.g-node.org/ ) or at least the doi (so we could query public services to provide that meta-data)

Thanks in advance!

**Comment by cgars** [comment]
I guess you refer to the GIN Server, therefore the answer below is not client related: 

Currently, we do not offer a specialized api routes for public or registered repositories (i might add them at some point in time). You can, however, **use the search api** as follows:
`https://web.gin.g-node.org/api/v1/repos/search`
which will return all public repositories as json, including a json string with a **ssh_url**. This can be used for "ssh cloning". 

Doified repositories contain a special file called either `cloudberry.yml` or `datacite.yml` which contains the **bibliographic metadata** used for registration. These **can be queried as follows**:
`https://web.gin.g-node.org/INT/multielectrode_grasp/raw/master/cloudberry.yml`
with the user and repository name changed accordingly.  The files are in YAML format and should look like [this](https://web.gin.g-node.org/G-Node/Info/src/master/datacite.yml). Not all repositories with such files are necessarily registered, however, and some (especially those from the doi user) will be forked repositories.

If you need more let me know and I can put it on either my to-implement or to-consider heap ;-).

**Comment by yarikoptic** [comment]
Great! thank you @cgars , I will check all those out!

**Comment by yarikoptic** [comment]
btw, that cloudberry.yml -- what is the "origin" of that specification?  there are some cloudberry projects I googled up but not sure if they relate anyhow

**Comment by yarikoptic** [comment]
@cgars @achilleas-k - is there an API end point for search?  prior mentioned one is no longer there.  Thanks in advance!

**Comment by yarikoptic** [comment]
FWIW there is https://github.com/gogs/docs-api which is probably what was used for the above /search endpoint which is no longer available.

**Comment by yarikoptic** [comment]
woohoo, attn @jwodder, I found some more recent email from @achilleas-k with seems more up to date info:
                                                                       
https://gin.g-node.org/api/v1/repos/search?limit=50                                       
                                                                                          
See also https://github.com/gogs/docs-api/tree/master/Repositories#search-repositories    
You can also do paging to get the list a few at a time.

**Comment by achilleas-k** [comment]
Hi @yarikoptic, thanks for finding this.  Didn't have a chance to catch up.  The search you linked now will only match repository names, so I hope that's enough for now.  The data search function doesn't have an API though.

**Comment by yarikoptic** [comment]
oh... our greedy interest is to find repos which would have `.datalad/config` file in them.  Name wouldn't be sufficient :-/

**Comment by yarikoptic** [comment]
filed https://github.com/gogs/gogs/issues/6594

**Comment by yarikoptic** [comment]
Is API  N/A temporarily or "for good"?:

```shell
❯ curl https://web.gin.g-node.org/api/v1/repos/search/?limit=10
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<p>Additionally, a 503 Service Unavailable
error was encountered while trying to use an ErrorDocument to handle the request.</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at web.gin.g-node.org Port 443</address>
</body></html>
```

**Comment by twachtler** [comment]
Hi @yarikoptic, please use https://gin.g-node.org/api/v1/repos/search/. "web.gin.g-node.org" urls are deprecated.

**Comment by yarikoptic** [comment]
Thank you @twachtler for the rapid response! (attn @candleindark to ^^^). 
I guess to list all repos we just need to iterate incrementing `?page=` option until `data` becomes empty, right?  or is there a better/recommended way?

**Comment by twachtler** [comment]
I guess so. But please do it on the weekend ;)

**Comment by yarikoptic** [comment]
deal! cron job then could run on weekends - no problem!
