### ISSUE TITLE
Make gin create more pure

### ISSUE THREAD

**Issue by The-E** [G-Node/gin-cli#143]
This is not something I _need_, just something that would be nice to have.

Right now, `gin create reponame` will try to create a new repository and then immediately create a checkout in the current working directory. For cleanliness' sake, it would be good if there was a mode that only creates the new repo without creating a checkout locally.

**Comment by achilleas-k** [comment]
Could be a flag, I guess. `gin create --no-clone` or similar.

**Comment by The-E** [comment]
That would be sufficient, yes

**Comment by achilleas-k** [comment]
Added in PR #160
