### ISSUE TITLE
"gin create" command does not work

### ISSUE THREAD

**Issue by galagoz** [G-Node/gin-cli#224]
Hi! I've recently downloaded the Gin Client to my Windows 10 laptop using the ["Quickstart: Local Gin Client" guidelines](https://web.gin.g-node.org/G-Node/info/wiki#quickstart-local-gin-client) with the following version:

![resim](https://user-images.githubusercontent.com/34252945/48179273-b3ced200-e31e-11e8-8e0b-9054ccf0aaca.png)

However, the `gin create` command doesn't work and gives this error:

![resim](https://user-images.githubusercontent.com/34252945/48179317-e7a9f780-e31e-11e8-935b-87e3360466bd.png)

I was wondering if I'm missing a step or if there's an actual problem. Thanks in advance!

**Comment by achilleas-k** [comment]
Definitely looks like a bug. Thanks. I'll have a look.
