### ISSUE TITLE
gin version fails on Windows systems

### ISSUE THREAD

**Issue by JiriVanek** [G-Node/gin-cli#249]
during checkout of older version of file with command "gin.exe version --id 557a6fec11701d93b389e7182c099e1137ad4d3e --copy-to c:\folder file.txt"
the command fails with this error:
fatal: relative path syntax can't be used outside working tree.
LOG:
Running shell command (Dir: C:\folder): git cat-file blob 557a6fe:./file.txt
Error during GitCatFile (Contents)
Version info:
GIN command line client 1.6 Build 001261 (33348957acdee79c99c147b75dedab34b5e12221)
  git: 2.20.0.windows.1
  git-annex: 6.20180927-gc5b6c55af

**Comment by JiriVanek** [comment]
also there is issue with error message. in stderr is no information and in stdout is no word "error".

**Comment by achilleas-k** [comment]
Please check this with the latest dev build and let me know if it's still the case.

**Comment by JiriVanek** [comment]
gin version command is now working with GIN command line client 1.7dev Build 001367 but if error occurs the stderr is still empty. currently checking error in stdout searching for "fatal" string

**Comment by achilleas-k** [comment]
Should I close this?

**Comment by JiriVanek** [comment]
yes, it is ok with gin-cli 1.7
