### ISSUE TITLE
windows problems

### ISSUE THREAD

**Issue by jcolomb** [G-Node/gin-cli#292]
We seem to have problems with gin-cli for windows (upload not working).

Plan: 
- get Keisuke to try debug
- see if datalad works
- contact datalad team to see whether they also add problems.

maybe put gin-cli in anaconda.

**Comment by jcolomb** [comment]
Most problems solved with the latest release of gin-cli, in beta at: https://gin.g-node.org/achilleas/gin-cli-builds 
@achilleas-k  can you confirm what version got to use internal openssh and git-annes, and if/when it will be the default gin-cli
then we can close this.

**Comment by achilleas-k** [comment]
Great to hear that it's working.  The PR is open here: https://github.com/G-Node/gin-cli/pull/301

Once I fix the issues with macOS (I'll probably move all the travis builds to GitHub actions) we can merge and releae.
