### ISSUE TITLE
Split out client library code

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-cli#30]
A new repository will be created for common code that will be shared between all user clients (e.g., `gin-client-lib`). This should contain most of the code found in this repository that is reusable, e.g., packages `client`, `repo`, `auth`.

The current repository, `gin-cli`, will then be a thin client on top of `gin-client-lib` which simply parses command line arguments, calls library functions, and handles output.

Other clients, like a desktop GUI or a filebrowser plugin, will also use `gin-client-lib` for all operations.

**Comment by mpsonntag** [comment]
We could also put this into a client specific package of the `gin-core` repository.
