### ISSUE TITLE
Unclear error about repo and gin clean compatbility 

### ISSUE THREAD

**Issue by h-mayorquin** [G-Node/gin-cli#330]
I try the following:

```bash
gin commit 4chDemoPLX.plx 
:: Adding file changes
   Nothing to do
:: Recording changes [error] git-annex: Repository /home/heberto/upload_gin/ephy_testing_data is at unsupported version 9. Upgrade git-annex.
```

So I somehow understand that my git-annex is to old (it is telling me to upgrade)

But then I check the version of git annex and get:

```bash
git annex version
git-annex version: 10.20240129
build flags: Assistant Webapp Pairing Inotify DBus DesktopNotify TorrentParser MagicMime Benchmark Feeds Testsuite S3 WebDAV
dependency versions: aws-0.24.1 bloomfilter-2.0.1.2 crypton-0.33 DAV-1.3.4 feed-1.3.2.1 ghc-9.4.7 http-client-0.7.14 persistent-sqlite-2.13.2.0 torrent-10000.1.3 uuid-1.3.15 yesod-1.6.2.1
key/value backends: ...
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs httpalso borg hook external
operating system: linux x86_64
supported repository versions: 8 9 10
upgrade supported from repository versions: 0 1 2 3 4 5 6 7 8 9 10
local repository version: 9
```
It is unclear what I needs to match. 

Probably related to this:
https://github.com/G-Node/gin-cli/issues/319

**Comment by twachtler** [comment]
Maybe you installed the GIN client via its Debian package, in which case it uses annex version 8. If so, deinstall and install the standalone GIN client (https://gin.g-node.org/G-Node/Info/wiki/GIN+CLI+Setup#binary-client-only). This will use the git annex you have installed on your system.

**Comment by h-mayorquin** [comment]
I am confused. The output of git annex version shows that is version 10.  Does it mean that gin uses different git-annex that that the one in my system?

**Comment by twachtler** [comment]
If you installed the Debian package, the client will use the git-annex that is bundeled in this package. Run `gin --version`, it will show you the  git-annex version the client uses. If you have a different version of git-annex already installed, it is recommended to install the client only, not the Debian package (https://gin.g-node.org/G-Node/Info/wiki/GIN+CLI+Setup#bundles-vs-client-only-packages).

**Comment by h-mayorquin** [comment]
> Run gin --version, it will show you the git-annex version the client uses

Thank you. I was aware of the distinction between the bundle and the stand-alone cli but I could not confirm which version gin was using. Using this I could see that it was still the bundled version. Purging and re-installing the cli tool did the job. 

I am closing this isue as the error makes sense to me now.
