### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-cli#56]
- [x] Document all options properly. Currently, all we have is the output of `gin cmdhelp` in the repo readme.
- [ ] Advanced documentation with explanation of what the client does in the background.
- [x] Create tutorial for common use cases.
- [ ] Add basic documentation into the packaged archives.

**Comment by JuliaSprenger** [comment]
I think it would help to add possible options for each status output gin is printing like git does it.
Eg for 
```bash
gin ls
Synced:

	README.md
	load_example.py

Locally modified (not uploaded):

	data/data0.mat
```
add  ```to upload data use 'gin upload <file>'```

**Comment by achilleas-k** [comment]
How's this?

```
No local content
(use "gin get-content <file>..." to download content)

Locally modified (not uploaded)
(use "gin upload <file>..." to upload changes)

Unlocked for editing
(use "gin lock <file>..." to lock file)

Untracked
(use "gin upload <file>..." to upload file and begin tracking)
```

Might change a bit with some upcoming changes, but it's a nice idea. Thanks.

**Comment by achilleas-k** [comment]
Updates to this issue:
- Help text in client (`gin help <cmd>`) is descriptive and includes examples.
- The [command translation](https://github.com/G-Node/gin-cli/blob/master/doc/command-translation.md) file is for advanced users and contributors to know what each gin command does in terms of git and git-annex internal commands.  So far it only includes a long description for the `upload` command.  The [doc directory](https://github.com/G-Node/gin-cli/tree/master/doc) contains more explanations about the client internals.
- The [gin-cli tutorial](https://web.gin.g-node.org/G-Node/Info/wiki/GinUsageTutorial#using-git-and-git-annex-directly) page on the GIN wiki also describes what git and git-annex settings the gin client sets up.
- The `gin ls` status headers describe steps that can be taken to change files from one state to another, as suggested (see PR #256)

Closing now.  Will open another issue for keeping the internal docs up to date.
