### ISSUE TITLE
Please add link to "gin.g-node.org" and "http://g-node.github.io/" to the Readmes of all gin-* repositories

### ISSUE THREAD

**Issue by dEvasEnApati** [G-Node/gin-cli#97]

**Comment by achilleas-k** [comment]
I just pushed a new README which links to the GIN main page and the quick start guide. Not sure about linking to the github.io page. Is there any particular reason you think it should link back to it? The github.io page is mainly a listing and description of our projects, so I don't know if it makes sense to link back to it from each project.

**Comment by dEvasEnApati** [comment]
I agree that links to the GIN main page and the quick start guide are sufficient enough to guide those who landed at this repository looking for usage details of GIN. Thanks!
